/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconLucidePlug: typeof import('~icons/lucide/plug.jsx').default
  const IconLucideSend: typeof import('~icons/lucide/send.jsx').default
  const IconLucideSettings2: typeof import('~icons/lucide/settings2.jsx').default
  const IconLucideSmilePlus: typeof import('~icons/lucide/smile-plus.jsx').default
}
