/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconLucideCheck: typeof import('~icons/lucide/check.jsx').default
  const IconLucideChevronDown: typeof import('~icons/lucide/chevron-down.jsx').default
  const IconLucideChevronsUpDown: typeof import('~icons/lucide/chevrons-up-down.jsx').default
  const IconLucideEye: typeof import('~icons/lucide/eye.jsx').default
  const IconLucidePlug: typeof import('~icons/lucide/plug.jsx').default
  const IconLucidePlus: typeof import('~icons/lucide/plus.jsx').default
  const IconLucideSend: typeof import('~icons/lucide/send.jsx').default
  const IconLucideSettings2: typeof import('~icons/lucide/settings2.jsx').default
  const IconLucideSmilePlus: typeof import('~icons/lucide/smile-plus.jsx').default
  const IconLucideX: typeof import('~icons/lucide/x.jsx').default
  const IconSimpleIconsSlack: typeof import('~icons/simple-icons/slack.jsx').default
}
