/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteImport } from './routes/dash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LinkXRouteImport } from './routes/link/x'
import { Route as InstallSlackRouteImport } from './routes/install/slack'
import { Route as ConnectTokenRouteImport } from './routes/connect/$token'
import { Route as ConfirmTokenRouteImport } from './routes/confirm/$token'

const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkXRoute = LinkXRouteImport.update({
  id: '/link/x',
  path: '/link/x',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallSlackRoute = InstallSlackRouteImport.update({
  id: '/install/slack',
  path: '/install/slack',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectTokenRoute = ConnectTokenRouteImport.update({
  id: '/connect/$token',
  path: '/connect/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmTokenRoute = ConfirmTokenRouteImport.update({
  id: '/confirm/$token',
  path: '/confirm/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dash': typeof DashRoute
  '/confirm/$token': typeof ConfirmTokenRoute
  '/connect/$token': typeof ConnectTokenRoute
  '/install/slack': typeof InstallSlackRoute
  '/link/x': typeof LinkXRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dash': typeof DashRoute
  '/confirm/$token': typeof ConfirmTokenRoute
  '/connect/$token': typeof ConnectTokenRoute
  '/install/slack': typeof InstallSlackRoute
  '/link/x': typeof LinkXRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dash': typeof DashRoute
  '/confirm/$token': typeof ConfirmTokenRoute
  '/connect/$token': typeof ConnectTokenRoute
  '/install/slack': typeof InstallSlackRoute
  '/link/x': typeof LinkXRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dash'
    | '/confirm/$token'
    | '/connect/$token'
    | '/install/slack'
    | '/link/x'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dash'
    | '/confirm/$token'
    | '/connect/$token'
    | '/install/slack'
    | '/link/x'
  id:
    | '__root__'
    | '/'
    | '/dash'
    | '/confirm/$token'
    | '/connect/$token'
    | '/install/slack'
    | '/link/x'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRoute
  ConfirmTokenRoute: typeof ConfirmTokenRoute
  ConnectTokenRoute: typeof ConnectTokenRoute
  InstallSlackRoute: typeof InstallSlackRoute
  LinkXRoute: typeof LinkXRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link/x': {
      id: '/link/x'
      path: '/link/x'
      fullPath: '/link/x'
      preLoaderRoute: typeof LinkXRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install/slack': {
      id: '/install/slack'
      path: '/install/slack'
      fullPath: '/install/slack'
      preLoaderRoute: typeof InstallSlackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/$token': {
      id: '/connect/$token'
      path: '/connect/$token'
      fullPath: '/connect/$token'
      preLoaderRoute: typeof ConnectTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm/$token': {
      id: '/confirm/$token'
      path: '/confirm/$token'
      fullPath: '/confirm/$token'
      preLoaderRoute: typeof ConfirmTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRoute,
  ConfirmTokenRoute: ConfirmTokenRoute,
  ConnectTokenRoute: ConnectTokenRoute,
  InstallSlackRoute: InstallSlackRoute,
  LinkXRoute: LinkXRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
