name: Setup pnpm
description: Setup pnpm and Node.js

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: tempoxyz/gh-actions/vendor/pnpm/action-setup@bd66336ead0e97e3939428f526dc61fb43db0996 # 2026-09-25T20-13-44Z-bd66336e

    - name: Setup node
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        cache: pnpm
        node-version: 24

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --ignore-scripts
