name: Setup pnpm
description: Setup pnpm and Node.js

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: tempoxyz/gh-actions/vendor/pnpm/action-setup@55fe3b63d9612623cc51e6c62d9d62fbcb175fb0 # 2026-09-29T01-25-15Z-55fe3b63

    - name: Setup node
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        cache: pnpm
        node-version: 24

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --ignore-scripts
