name: Production

on:
  push:
    branches: [main]

permissions: {}

env:
  WRANGLER_SEND_METRICS: false

jobs:
  check:
    name: Check
    permissions:
      contents: read
    uses: ./.github/workflows/check.yml
    with:
      skip_workers: true

  deploy:
    name: Deploy
    needs: check
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Run migrations
        run: pnpm exec wrangler d1 migrations apply tipbot --env production --remote
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Build
        run: pnpm build
        env:
          CLOUDFLARE_ENV: production
          SLACK_APP_ID: ${{ vars.SLACK_APP_ID }}

      - name: Deploy to Production
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env production
          environment: production
          secrets: |
            FEE_PAYER_PRIVATE_KEY_MAINNET
            FEE_PAYER_PRIVATE_KEY_TESTNET
            SECRET_KEY
            SLACK_CLIENT_ID
            SLACK_CLIENT_SECRET
            SLACK_SIGNING_SECRET
            TWITTER_ACCESS_TOKEN
            TWITTER_ACCESS_TOKEN_SECRET
            TWITTER_BEARER_TOKEN
            TWITTER_CONSUMER_KEY
            TWITTER_CONSUMER_SECRET
            TWITTER_OAUTH_CLIENT_ID
            TWITTER_OAUTH_CLIENT_SECRET
        env:
          FEE_PAYER_PRIVATE_KEY_MAINNET: ${{ secrets.FEE_PAYER_PRIVATE_KEY_MAINNET }}
          FEE_PAYER_PRIVATE_KEY_TESTNET: ${{ secrets.FEE_PAYER_PRIVATE_KEY_TESTNET }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SLACK_APP_ID: ${{ vars.SLACK_APP_ID }}
          SLACK_CLIENT_ID: ${{ secrets.SLACK_CLIENT_ID }}
          SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_OAUTH_CLIENT_ID: ${{ secrets.TWITTER_OAUTH_CLIENT_ID }}
          TWITTER_OAUTH_CLIENT_SECRET: ${{ secrets.TWITTER_OAUTH_CLIENT_SECRET }}

  update_slack_app:
    name: Update Slack App
    needs: deploy
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: slack-config-ci
      cancel-in-progress: false
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Setup Slack config token
        id: slack_token
        uses: ./.github/actions/setup-slack-config-token
        with:
          github-token: ${{ secrets.SLACK_GH_TOKEN }}
          slack-config-refresh-token: ${{ secrets.SLACK_CONFIG_REFRESH_TOKEN }}
          slack-config-access-token: ${{ secrets.SLACK_CONFIG_ACCESS_TOKEN }}

      - name: Update Slack production app
        env:
          SLACK_APP_ID: ${{ vars.SLACK_APP_ID }}
          SLACK_CONFIG_ACCESS_TOKEN: ${{ steps.slack_token.outputs.token }}
        run: pnpm slack:app update production tip.bot "$SLACK_APP_ID"
