name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions: {}

concurrency:
  group: pull-request-${{ github.event.pull_request.number }}
  cancel-in-progress: false

env:
  WRANGLER_SEND_METRICS: false

jobs:
  check:
    name: Check
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/check.yml
