name: zizmor

on:
  pull_request:
    branches: ['**']
  push:
    branches: [main]

permissions: {}

jobs:
  zizmor:
    name: zizmor
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: tempoxyz/gh-actions/vendor/zizmorcore/zizmor-action@6f436eb3a168279692739e8c0c9fdb52b94bfae7
        with:
          # TODO: Remove this once the repo is public or GitHub Advanced Security is enabled.
          advanced-security: false
